"""Canonical spatial evidence contracts, mapping and persistence."""
from caereflex.spatial.contracts import (
    SPATIAL_GRAPH_VERSION,
    AxisAlignedBounds,
    CoordinateFrame,
    CoordinateHandedness,
    SpatialArrayLink,
    SpatialArrayRole,
    SpatialContractError,
    SpatialDomain,
    SpatialEntity,
    SpatialEntityKind,
    SpatialEvidenceRecord,
    SpatialEvidenceStatus,
    SpatialGraph,
    SpatialGraphRef,
    SpatialGraphSnapshot,
    SpatialGraphStatus,
    SpatialRelation,
    SpatialRelationKind,
    SpatialReviewStatus,
)
from caereflex.spatial.mapping import (
    MappingPolicy,
    SpatialMappingError,
    map_execution_result,
    map_gmsh,
    map_openfoam,
    map_vtk,
)
from caereflex.spatial.service import attach_spatial_graph_ref, map_persist_attach, spatial_graph_refs
from caereflex.spatial.store import SpatialStore, SpatialStoreError

__all__ = [
    "SPATIAL_GRAPH_VERSION",
    "AxisAlignedBounds",
    "CoordinateFrame",
    "CoordinateHandedness",
    "MappingPolicy",
    "SpatialArrayLink",
    "SpatialArrayRole",
    "SpatialContractError",
    "SpatialDomain",
    "SpatialEntity",
    "SpatialEntityKind",
    "SpatialEvidenceRecord",
    "SpatialEvidenceStatus",
    "SpatialGraph",
    "SpatialGraphRef",
    "SpatialGraphSnapshot",
    "SpatialGraphStatus",
    "SpatialMappingError",
    "SpatialRelation",
    "SpatialRelationKind",
    "SpatialReviewStatus",
    "SpatialStore",
    "SpatialStoreError",
    "attach_spatial_graph_ref",
    "map_execution_result",
    "map_gmsh",
    "map_openfoam",
    "map_persist_attach",
    "map_vtk",
    "spatial_graph_refs",
]
