"""Canonical spatial evidence contracts and persistence."""
from caereflex.spatial.contracts import (
    SPATIAL_GRAPH_VERSION,
    AxisAlignedBounds,
    CoordinateFrame,
    CoordinateHandedness,
    SpatialArrayLink,
    SpatialArrayRole,
    SpatialContractError,
    SpatialDomain,
    SpatialEntity,
    SpatialEntityKind,
    SpatialEvidenceRecord,
    SpatialEvidenceStatus,
    SpatialGraph,
    SpatialGraphRef,
    SpatialGraphSnapshot,
    SpatialGraphStatus,
    SpatialRelation,
    SpatialRelationKind,
    SpatialReviewStatus,
)
from caereflex.spatial.service import attach_spatial_graph_ref, spatial_graph_refs
from caereflex.spatial.store import SpatialStore, SpatialStoreError

__all__ = [
    "SPATIAL_GRAPH_VERSION",
    "AxisAlignedBounds",
    "CoordinateFrame",
    "CoordinateHandedness",
    "SpatialArrayLink",
    "SpatialArrayRole",
    "SpatialContractError",
    "SpatialDomain",
    "SpatialEntity",
    "SpatialEntityKind",
    "SpatialEvidenceRecord",
    "SpatialEvidenceStatus",
    "SpatialGraph",
    "SpatialGraphRef",
    "SpatialGraphSnapshot",
    "SpatialGraphStatus",
    "SpatialRelation",
    "SpatialRelationKind",
    "SpatialReviewStatus",
    "SpatialStore",
    "SpatialStoreError",
    "attach_spatial_graph_ref",
    "spatial_graph_refs",
]
